sudo: required
services:
- docker
language: bash
script:
# prepare qemu - wat
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t elie195/rpi-mongo .
# test image
- docker run elie195/rpi-mongo mongo --version
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "ENV MONGO_VERSION" Dockerfile | awk 'NF>1{print $NF}')
    docker tag elie195/rpi-mongo elie195/rpi-mongo:$TAG
    docker push elie195/rpi-mongo:$TAG
    docker push elie195/rpi-mongo
  fi
